<font size = 5 color = 'blue' ><b>NMF : non- negative matrix factorization</b> </font>

In [15]:
from sklearn.decomposition import NMF
import numpy as np

<b>if k  = 3 :👇</b>

In [41]:
V = np.array([[2, 0, 2, 1], 
              [1, 2, 1, 2], 
              [1, 1, 0, 2],
              [0, 5, 4, 2],
              [9, 2, 0, 0],
              [10, 0, 1,0],])


model = NMF(n_components=3)
W = model.fit_transform(V)  # جدول الگوها
H = model.components_       # جدول ترکیب‌ها

W =  np.round(W, 3)
H =  np.round(H, 3)

print("الگوها (W):\n", W,"\n")
print("ترکیب‌ها (H):\n", H,"\t")

الگوها (W):
 [[0.222 0.342 0.   ]
 [0.    0.647 0.247]
 [0.    0.333 0.245]
 [0.    1.628 0.01 ]
 [0.    0.    2.211]
 [0.989 0.    0.124]] 

ترکیب‌ها (H):
 [[9.572 0.    1.221 0.079]
 [0.    2.893 2.351 1.675]
 [4.07  0.888 0.    0.112]] 	


In [42]:
V = np.array([[2, 0, 2, 1], 
              [1, 2, 1, 2], 
              [1, 1, 0, 2],
              [0, 5, 4, 2],
              [9, 2, 0, 0],
              [10, 0, 1,0],])
new_V = np.dot(W, H)
new_V

array([[2.124984, 0.989406, 1.075104, 0.590388],
       [1.00529 , 2.091107, 1.521097, 1.111389],
       [0.99715 , 1.180929, 0.782883, 0.585215],
       [0.0407  , 4.718684, 3.827428, 2.72802 ],
       [8.99877 , 1.963368, 0.      , 0.247632],
       [9.971388, 0.110112, 1.207569, 0.092019]])

In [43]:
sub = np.subtract(V,new_V)
eq = np.square(sub)
error= np.sum(eq)
error =  np.round(error, 3)
print(error)

6.502


<b>if k  = 4 :👇</b>

In [44]:
V = np.array([[2, 0, 2, 1], 
              [1, 2, 1, 2], 
              [1, 1, 0, 2],
              [0, 5, 4, 2],
              [9, 2, 0, 0],
              [10, 0, 1,0],])


model = NMF(n_components=4)
W = model.fit_transform(V)  # جدول الگوها
H = model.components_       # جدول ترکیب‌ها

W =  np.round(W, 3)
H =  np.round(H, 3)

print("الگوها (W):\n", W,"\n")
print("ترکیب‌ها (H):\n", H,"\t")

الگوها (W):
 [[0.164 0.528 0.137 0.   ]
 [0.082 0.264 0.28  0.643]
 [0.082 0.    0.283 0.322]
 [0.    1.056 0.272 1.609]
 [0.737 0.    0.    0.643]
 [0.819 0.264 0.    0.   ]] 

ترکیب‌ها (H):
 [[1.2205e+01 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 3.7870e+00 6.2000e-02]
 [0.0000e+00 0.0000e+00 0.0000e+00 7.0690e+00]
 [0.0000e+00 3.1080e+00 0.0000e+00 7.0000e-03]] 	


In [45]:
V = np.array([[2, 0, 2, 1], 
              [1, 2, 1, 2], 
              [1, 1, 0, 2],
              [0, 5, 4, 2],
              [9, 2, 0, 0],
              [10, 0, 1,0],])
new_V = np.dot(W, H)
new_V

array([[2.001620e+00, 0.000000e+00, 1.999536e+00, 1.001189e+00],
       [1.000810e+00, 1.998444e+00, 9.997680e-01, 2.000189e+00],
       [1.000810e+00, 1.000776e+00, 0.000000e+00, 2.002781e+00],
       [0.000000e+00, 5.000772e+00, 3.999072e+00, 1.999503e+00],
       [8.995085e+00, 1.998444e+00, 0.000000e+00, 4.501000e-03],
       [9.995895e+00, 0.000000e+00, 9.997680e-01, 1.636800e-02]])

In [46]:
sub = np.subtract(V,new_V)
eq = np.square(sub)
error= np.sum(eq)
error =  np.round(error, 3)
print(error)

0.0


<b>if k  = 2 :👇</b>

In [47]:
V = np.array([[2, 0, 2, 1], 
              [1, 2, 1, 2], 
              [1, 1, 0, 2],
              [0, 5, 4, 2],
              [9, 2, 0, 0],
              [10, 0, 1,0],])


model = NMF(n_components=2)
W = model.fit_transform(V)  # جدول الگوها
H = model.components_       # جدول ترکیب‌ها

W =  np.round(W, 3)
H =  np.round(H, 3)

print("الگوها (W):\n", W,"\n")
print("ترکیب‌ها (H):\n", H,"\t")

الگوها (W):
 [[3.060e-01 4.510e-01]
 [1.500e-01 8.870e-01]
 [1.490e-01 4.760e-01]
 [2.000e-03 2.136e+00]
 [1.393e+00 3.000e-01]
 [1.544e+00 0.000e+00]] 

ترکیب‌ها (H):
 [[6.472e+00 3.400e-01 2.220e-01 0.000e+00]
 [4.000e-03 2.261e+00 1.732e+00 1.269e+00]] 	


In [48]:
V = np.array([[2, 0, 2, 1], 
              [1, 2, 1, 2], 
              [1, 1, 0, 2],
              [0, 5, 4, 2],
              [9, 2, 0, 0],
              [10, 0, 1,0],])
new_V = np.dot(W, H)
new_V

array([[1.982236, 1.123751, 0.849064, 0.572319],
       [0.974348, 2.056507, 1.569584, 1.125603],
       [0.966232, 1.126896, 0.85751 , 0.604044],
       [0.021488, 4.830176, 3.699996, 2.710584],
       [9.016696, 1.15192 , 0.828846, 0.3807  ],
       [9.992768, 0.52496 , 0.342768, 0.      ]])

In [49]:
sub = np.subtract(V,new_V)
eq = np.square(sub)
error= np.sum(eq)
error =  np.round(error, 3)
print(error)

9.448
